In [1]:
import numpy as np

In [160]:
A = np.array([[2, 1],[5, 7]])
b = np.array([11,13])

np.linalg.solve(A,b)

array([ 7.11111111, -3.22222222])

In [161]:
L = np.tril(A, -1)
D = np.diag(np.diag(A))
U = np.triu(A, 1)

In [163]:
# Jacobiova

x = np.zeros(len(A))

for i in range(20):
    x = np.matmul(np.linalg.inv(D), (b - np.matmul(L+U, x) ))
    print(i, x)

0 [5.5        1.85714286]
1 [ 4.57142857 -2.07142857]
2 [ 6.53571429 -1.40816327]
3 [ 6.20408163 -2.81122449]
4 [ 6.90561224 -2.57434402]
5 [ 6.78717201 -3.07543732]
6 [ 7.03771866 -2.99083715]
7 [ 6.99541858 -3.16979904]
8 [ 7.08489952 -3.1395847 ]
9 [ 7.06979235 -3.20349966]
10 [ 7.10174983 -3.19270882]
11 [ 7.09635441 -3.21553559]
12 [ 7.1077678  -3.21168172]
13 [ 7.10584086 -3.21983414]
14 [ 7.10991707 -3.21845776]
15 [ 7.10922888 -3.22136934]
16 [ 7.11068467 -3.22087777]
17 [ 7.11043889 -3.22191762]
18 [ 7.11095881 -3.22174206]
19 [ 7.11087103 -3.22211344]


In [164]:
# Gauss-Seidlerova

x = np.zeros(len(A))

for i in range(20):
    x = np.matmul(np.linalg.inv(D+L), (b - np.matmul(U, x)))
    print(i, x)

0 [ 5.5        -2.07142857]
1 [ 6.53571429 -2.81122449]
2 [ 6.90561224 -3.07543732]
3 [ 7.03771866 -3.16979904]
4 [ 7.08489952 -3.20349966]
5 [ 7.10174983 -3.21553559]
6 [ 7.1077678  -3.21983414]
7 [ 7.10991707 -3.22136934]
8 [ 7.11068467 -3.22191762]
9 [ 7.11095881 -3.22211344]
10 [ 7.11105672 -3.22218337]
11 [ 7.11109168 -3.22220835]
12 [ 7.11110417 -3.22221727]
13 [ 7.11110863 -3.22222045]
14 [ 7.11111023 -3.22222159]
15 [ 7.1111108 -3.222222 ]
16 [ 7.111111   -3.22222214]
17 [ 7.11111107 -3.22222219]
18 [ 7.1111111  -3.22222221]
19 [ 7.11111111 -3.22222222]


In [151]:
A = np.array([[1,3,3], [4,3,6], [7,8,9]])
b = np.array([8,6,8])

L = np.tril(A, -1)
D = np.diag(np.diag(A))
U = np.triu(A, 1)


In [157]:
x = np.zeros(len(A))

for i in range(100):
    x = np.matmul(np.linalg.inv(D), (b - np.matmul(L + U, x) ))
print(x)
np.linalg.solve(A,b)

[-2.32673134e+51 -1.55115423e+51 -9.77829523e+50]


array([-3.8       ,  0.8       ,  3.13333333])