In [1]:
import numpy as np

In [47]:
u = np.array([4, 2, 1])
v = np.array([1, 2, 3])

def sc_soucin(u, v):
    soucin = [u[i]*v[i] for i in range(len(u))]
    return sum(soucin)

print(sc_soucin(u, v))
print(np.dot(u, v))

11
11


In [27]:
u = np.array([4, 2, 1])
v = np.array([1, 2, 3])

# for i in range(len(u)):
#     print(i)
# slozky = []
# for i in range(len(u)):
#     slozky[i] = (u[i-1]*v[i] - v[i-1]*u[i])
    # c = np.array([(u[1]*v[2] - v[1]*u[2]), (u[2]*v[0] - v[2]*u[0]), (u[0]*v[1] - v[0]*u[1])])
for i in u:
    for j in


# print(vc_soucin(u, v))
print(np.cross(u, v))

0
1
2


IndexError: list assignment index out of range

In [48]:
u = np.array([4, 2, 1])
v = np.array([1, 2, 3])

def ten_souc(u, v):
    mat = np.zeros((len(u),len(u)))
    for i in range(len(u)):
        for j in range(len(v)):
            mat[i, j] = u[i] * v[j]
    return mat

print(ten_souc(u,v))
print(np.tensordot(u, v, 0))

[[ 4.  8. 12.]
 [ 2.  4.  6.]
 [ 1.  2.  3.]]
[[ 4  8 12]
 [ 2  4  6]
 [ 1  2  3]]


In [64]:
# nasobeni matic

a = np.array([
    [1,2],
    [3,4],
    [5,6]
])

b = np.array([
    [1,2,3],
    [4,5,6]
])

b_t = b.T

matice = np.zeros((3,3))

prvky = []

for i in a:
    for j in b_t:
        prvky.append(sum(i * j))

print(prvky[0:3])
print(prvky[3:6])
print(prvky[6:10])

[9, 12, 15]
[19, 26, 33]
[29, 40, 51]


In [56]:
a = np.array([
    [1,2],
    [3,4],
    [5,6]
])

b = np.array([
    [1,2,3],
    [4,5,6]
])

print(np.matmul(a, b))

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [81]:
A = np.array([
    [3,2,1],
    [2,3,1],
    [2,1,3]
])
A_t = A.T

b = np.array([5,1,11])

det_A = np.linalg.det(A)

for i in range(3):
    seznam = 
    

[[ 5  1 11]
 [ 2  3  1]
 [ 1  1  3]]
[[ 5  1 11]
 [ 5  1 11]
 [ 1  1  3]]
[[ 5  1 11]
 [ 5  1 11]
 [ 5  1 11]]
