In [12]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
from numpy.random import choice



mesta = ['Chabarovice', 'Usti nad Labem', 'Praha', 'Brno', 'Karlovy Vary']

matice = np.matrix(
    [
        [0, 10, 92, 296, 111],
        [10, 0, 91, 295, 119],
        [92, 91, 0, 205, 129],
        [296, 295, 205, 0, 336],
        [111, 119, 129, 336, 0],
    ]
)

In [ ]:
G = nx.DiGraph(matice_sousednosti)
nx.draw(G)
plt.show()

In [25]:
def gen_jedinec(matice):
    mesta = [i for i in range(len(matice))]
    cesta = choice(len(matice), size=len(matice), replace=False)
    return cesta

jedinci = []
for i in range(len(matice)):
    jedinci.append(gen_jedinec(matice))


In [26]:
def ohodnoceni(jedinci, matice):
    for i in jedinci:

[array([0, 2, 3, 4, 1]),
 array([4, 0, 3, 2, 1]),
 array([2, 3, 1, 4, 0]),
 array([3, 1, 4, 2, 0]),
 array([3, 4, 2, 0, 1])]